CREATE SEQUENCE IF NOT EXISTS SEQ_CONTACT AS INTEGER
    MINVALUE 1
    MAXVALUE 99999999
    INCREMENT_BY 10
    START WITH 1
    NOCACHE
    NOCYCLE;


CREATE TABLE IF NOT EXISTS CONTACT (
                                       ID INTEGER NOT NULL DEFAULT (NEXT VALUE FOR SEQ_CONTACT),
    NAME VARCHAR(150) NOT NULL,
    NICKNAME VARCHAR(100) NOT NULL,
    BIRTH_DAY DATE,
    PRIMARY KEY (ID)
    );
